### PR TITLE
Update the updater script

### PR DESCRIPTION
**Pull request by glensc**
### Description

recent updates (efb892b) made the logic broken. it would no longer catch updates because submodule pointer is never updated.

also made some other fixes:
- fix changelog to note actual changes
- generate directly to real path needed
- include diffstat to commit message
- creates signed commits
- cleaned up from the `next` branch being no longer used
- switches lvm2 remote to master

### Check List

- [x] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

### CODE REVIEW

**Comment by glensc** [comment]
it's super annoying to find that the commits are not signed off, and the provided link doesn't even give you commandline to sign off them all.

at least when dco was used in docker project, there was commandline example how to rebase all commits.

cc @tas50

**Comment by glensc** [comment]
also, please yank 0.2.5 release as noted here: https://github.com/chef/chef-ruby-lvm-attrib/pull/8#issuecomment-435606151

**Comment by glensc** [comment]
cc @tas50

**Comment by bdwyertech** [comment]
Yeah, this is definitely a bug.

I think the proper fix for the submodule piece is this though:

#### Before
```shell
git submodule update --init --recursive
```
#### After
```shell
git submodule update --init --remote --recursive
```

**Pull request merged**
